force-app/main/default/objects/CallRevu_Lead__c/CallRevu_Lead__c.object-meta.xml
<CustomObject>
    <label>CallRevu Lead</label>
    <nameField>
        <label>CallRevu Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CallRevu Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CallRevu_Lead__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CallRevu Leads</relationshipLabel>
    <relationshipName>CallRevu_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactActivitiesTest.cls
/*
    Developer:  Jim Hyland <jon@shippconsulting.com>
    
    Description:
       Tests for ContactActivitiesController
*/
@isTest
public class ContactActivitiesTest {

    /* Test Methods */
    
@isTest
    private static void testContactActivitiesController() {
        
        // set up test data
        Contact contact = TestUtil.createContact();
        insert new Task(WhoId = contact.Id, status = 'Completed');
        CallRevu_Lead__c testLead = new CallRevu_Lead__c(contact__c = contact.Id, name = 'Lead');
        insert testLead;
        
        // run tests
        ApexPages.Standardcontroller sc3 = new ApexPages.StandardController(testLead);
        ContactActivitiesController con = new ContactActivitiesController(sc3);
        ContactActivitiesController.getActivityRecords('Task', 'CallRevu_Leads', testLead.Id, 'Completed');
    }    
}