force-app/main/default/objects/Apex_SLAs__c/Apex_SLAs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Apex SLAs</label>
</CustomObject>

force-app/main/default/objects/Apex_SLAs__c/fields/Critical_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>Critical_Priority_Response_Hours__c</fullName>
    <label>Critical Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_SLAs__c/fields/High_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>High_Priority_Response_Hours__c</fullName>
    <label>High Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_SLAs__c/fields/Low_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>Low_Priority_Response_Hours__c</fullName>
    <label>Low Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_SLAs__c/fields/Medium_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>Medium_Priority_Response_Hours__c</fullName>
    <label>Medium Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
@isTest
private class CaseTriggerTest {

    @isTest
    private static void testCaseTriggerHelper() {
        
        // set up test data
        Case testCase = TestUtil.generateCase();
        testCase.Type = 'Archived Salesforce Cases';
        testCase.Priority = 'Low';
        testCase.Case_Subtype__c = 'Add Employee';
        Apex_SLAs__c existingSLA = [SELECT Id FROM Apex_SLAs__c LIMIT 1];
        existingSLA.Critical_Priority_Response_Hours__c = 1;
        existingSLA.High_Priority_Response_Hours__c = 1;
        existingSLA.Medium_Priority_Response_Hours__c = 1;
        existingSLA.Low_Priority_Response_Hours__c = 1;
        update existingSLA;
        
        // run tests
        insert testCase;
        testCase.Priority = 'High';
        testCase.Initial_Response_Date_Time__c = system.now();
        update testCase;
    }
}