force-app/main/default/objects/Apex_SLAs__c/Apex_SLAs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Apex SLAs</label>
</CustomObject>

force-app/main/default/objects/Apex_SLAs__c/fields/Critical_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>Critical_Priority_Response_Hours__c</fullName>
    <label>Critical Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_SLAs__c/fields/High_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>High_Priority_Response_Hours__c</fullName>
    <label>High Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_SLAs__c/fields/Low_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>Low_Priority_Response_Hours__c</fullName>
    <label>Low Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_SLAs__c/fields/Medium_Priority_Response_Hours__c.field-meta.xml
<CustomField>
    <fullName>Medium_Priority_Response_Hours__c</fullName>
    <label>Medium Priority Response (Hours)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseSubjectDeleteTest.cls
@isTest (SeeAllData=true)
public class CaseSubjectDeleteTest {
    
    @isTest
    public static void testCaseDelete(){
       /* Apex_SLAs__c testSla = new Apex_SLAs__c(Critical_Priority_Response_Hours__c=1, High_Priority_Response_Hours__c=2, Medium_Priority_Response_Hours__c=3, 
            Low_Priority_Response_Hours__c=4);
        insert testSla;*/

        Case testCase = new Case(subject = 'Auto Reply',Type = 'Archived Salesforce Cases',
        Case_Subtype__c = 'Add Employee');
        insert testCase; 
        system.debug('testCase: ' + testCase);
        
        Case testCase2 = new Case(subject = 'Delivery Failur',Type = 'Archived Salesforce Cases',
        Case_Subtype__c = 'Add Employee');
        insert testCase2; 
       
        
        list <Case> caseQuery1 = [Select Id from Case where Id = :testCase.Id];
        list <Case> caseQuery2 = [Select Id from Case where Id = :testCase2.Id];
        
        // both will be one since case deletion needed to be moved to a future method
        system.assert(caseQuery1.size() ==1);
        system.assert(caseQuery2.size() ==1); 
        
    }

}