force-app/main/default/objects/Billing_Agreement__c/Billing_Agreement__c.object-meta.xml
<CustomObject>
    <description>Billing Agreements associated with Service Agreements</description>
    <label>Billing Agreement</label>
    <nameField>
        <label>Billing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Agreement__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Agreements</relationshipLabel>
    <relationshipName>Billing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Agreement__c/fields/Next_Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Start_Date__c</fullName>
    <label>Next Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Agreement__c/fields/Ready_To_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_To_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready To Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Agreement__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Billing Agreements</relationshipLabel>
    <relationshipName>Billing_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <label>Service Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement__c/fields/Authorization_Contact__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorization Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CallRevu_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Bill_to_Share_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Share_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Share Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CallRevu_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/CRM__c.field-meta.xml
<CustomField>
    <fullName>CRM__c</fullName>
    <label>CRM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advent</fullName>
            </value>
            <value>
                <fullName>Arcadium (Partnered with CDK)</fullName>
            </value>
            <value>
                <fullName>AutoSoft</fullName>
            </value>
            <value>
                <fullName>CarResearch</fullName>
            </value>
            <value>
                <fullName>CDK</fullName>
            </value>
            <value>
                <fullName>Contact Management (Reynolds)</fullName>
            </value>
            <value>
                <fullName>CRM Suite</fullName>
                <label>CRM Suite (iMagic)</label>
            </value>
            <value>
                <fullName>D2C Media</fullName>
            </value>
            <value>
                <fullName>DealerMine</fullName>
            </value>
            <value>
                <fullName>DealerPeak</fullName>
            </value>
            <value>
                <fullName>DealerSocket</fullName>
            </value>
            <value>
                <fullName>Dominion (AutoBase CRMSuite)</fullName>
            </value>
            <value>
                <fullName>DriveCentric</fullName>
            </value>
            <value>
                <fullName>eLead1</fullName>
            </value>
            <value>
                <fullName>FourOneLabs</fullName>
            </value>
            <value>
                <fullName>HigherGear</fullName>
            </value>
            <value>
                <fullName>Interactive360</fullName>
            </value>
            <value>
                <fullName>LIS CRM</fullName>
            </value>
            <value>
                <fullName>Momentum</fullName>
            </value>
            <value>
                <fullName>Oplogic</fullName>
            </value>
            <value>
                <fullName>ProMax</fullName>
            </value>
            <value>
                <fullName>VinSolutions</fullName>
            </value>
            <value>
                <fullName>Votenza</fullName>
            </value>
            <value>
                <fullName>ZoHo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current Call Tracker Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CallBright</fullName>
            </value>
            <value>
                <fullName>CallFire</fullName>
            </value>
            <value>
                <fullName>CallRail</fullName>
            </value>
            <value>
                <fullName>CallSource</fullName>
            </value>
            <value>
                <fullName>Car Wars/Call Box/CI</fullName>
            </value>
            <value>
                <fullName>CRM - Dominion Vision/Direct Connect</fullName>
            </value>
            <value>
                <fullName>CRM - VinSolutions/Call Tracking</fullName>
            </value>
            <value>
                <fullName>DialogTech</fullName>
            </value>
            <value>
                <fullName>IAT/InteractiveTel</fullName>
            </value>
            <value>
                <fullName>Marchex</fullName>
            </value>
            <value>
                <fullName>Marcom Results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>ProActive Dealer Solutions</fullName>
            </value>
            <value>
                <fullName>RingDNA</fullName>
            </value>
            <value>
                <fullName>Who’sCalling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Preferred_Contact_For_Billing__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Contact_For_Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Contact For Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement (Service Location)</relationshipLabel>
    <relationshipName>Service_Agreement2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/Service_Agreement_Products__c.object-meta.xml
<CustomObject>
    <label>Service Agreement Products</label>
    <nameField>
        <label>Contract Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreement Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement Products</relationshipLabel>
    <relationshipName>Service_Agreement_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Bill_to_Share_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Share_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Share Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement Products (Bill-to Share Account)</relationshipLabel>
    <relationshipName>Service_Agreement_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Billing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Billing_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Agreement</label>
    <referenceTo>Billing_Agreement__c</referenceTo>
    <relationshipLabel>Service Agreement Products</relationshipLabel>
    <relationshipName>Service_Agreement_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/CallRevu_Contract__c.field-meta.xml
<CustomField>
    <fullName>CallRevu_Contract__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Service Agreement Products</relationshipLabel>
    <relationshipName>Service_Agreement_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Invoice_Type_To_Create__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_To_Create__c</fullName>
    <label>Invoice Type To Create</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Invoice</fullName>
            </value>
            <value>
                <fullName>Last Invoice</fullName>
            </value>
            <value>
                <fullName>Monthly Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Next_Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Start_Date__c</fullName>
    <description>Calculated By Workflow</description>
    <label>Next Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/PriceBookEntryID__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryID__c</fullName>
    <label>PriceBookEntryID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Contract_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Ready_To_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_To_Invoice__c</fullName>
    <formula>!isblank(  text(Invoice_Type_To_Create__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ready To Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateOrderFromAgreementTest.cls
/*
    Developer: Jim Hyland <jon@shippconsulting.com>
    
    Description:
       Tests for CreateOrderFromAgreementController and CreateOrderFromAgreement_Batch
*/
@isTest
public class CreateOrderFromAgreementTest {

    /* Variables */
    
    private static Billing_Agreement__c billing;
    private static Service_Agreement__c contract;

    /* Test Methods */
    
    static {
        
        // set up test data
        Account account = TestUtil.createAccount();
        Contact contact = TestUtil.createContact();
        Product2 theProduct = TestUtil.createProduct();
        contract = new Service_Agreement__c(Service_Location__c = account.Id, Authorization_Contact__c = contact.Id,
            crm__c = 'eLead1', Preferred_Contact_For_Billing__c = contact.Id, current__c = 'CallBright', bill_to_account__c = account.Id,
            Bill_To_Share_Account__c = account.Id, Price_Book__c = Test.getStandardPricebookId(), is_test__c = true);
        insert contract;
        PricebookEntry entry = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), product2Id = theProduct.Id, unitPrice = 1, 
            is_test__c = true); 
        insert entry;
        billing = new Billing_Agreement__c(Service_Agreement__c = contract.Id, Next_Billing_Start_Date__c = system.today().toStartOfMonth(),
            ready_to_invoice__c = true);
        insert billing;
        Service_Agreement_Products__c product = new Service_Agreement_Products__c(CallRevu_Contract__c = contract.Id, 
            product__c = theProduct.Id, next_billing_date__c = system.today(), bill_to_account__c = account.Id, MRR__c = 1,
            Bill_To_Share_Account__c = account.Id, Effective_Date__c = system.today().toStartOfMonth(), 
            End_Date__c = system.today().toStartOfMonth().addDays(27), quantity__c = 1, 
            Price_Per_Unit__c = 1, PricebookEntryId__c = entry.Id, invoice_type_to_create__c = 'Monthly',  is_test__c = true);
        insert product; 
    }
    
    @isTest
    private static void testCreateOrderFromAgreementController() {
        
        // run tests
        CreateOrderFromAgreementController con = new CreateOrderFromAgreementController();
    /*    CreateOrderFromAgreementController.setupComponent();*/
    /*    String year = String.valueOf(system.today().year()); */
        Test.startTest();
        CreateOrderFromAgreementController.CreateOrderReturn orderReturn = CreateOrderFromAgreementController.buildOrder(contract.Id,/* 'January', year,*/
            true); 
        Test.stopTest(); 
        CreateOrderFromAgreementController.CreateOrderReturn billingReturn = CreateOrderFromAgreementController.buildOrderFromBilling(billing.Id);
    }
}