force-app/main/default/objects/Billing_Agreement__c/Billing_Agreement__c.object-meta.xml
<CustomObject>
    <description>Billing Agreements associated with Service Agreements</description>
    <label>Billing Agreement</label>
    <nameField>
        <label>Billing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Agreement__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Agreements</relationshipLabel>
    <relationshipName>Billing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Agreement__c/fields/Next_Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Start_Date__c</fullName>
    <label>Next Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Agreement__c/fields/Ready_To_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_To_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready To Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Agreement__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Billing Agreements</relationshipLabel>
    <relationshipName>Billing_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <label>Service Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CallRevu_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Last_Opportunity_Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Last_Opportunity_Change_Type__c</fullName>
    <label>Last Opportunity Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement (Service Location)</relationshipLabel>
    <relationshipName>Service_Agreement2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/Service_Agreement_Products__c.object-meta.xml
<CustomObject>
    <label>Service Agreement Products</label>
    <nameField>
        <label>Contract Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreement Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement Products</relationshipLabel>
    <relationshipName>Service_Agreement_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Billing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Billing_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Agreement</label>
    <referenceTo>Billing_Agreement__c</referenceTo>
    <relationshipLabel>Service Agreement Products</relationshipLabel>
    <relationshipName>Service_Agreement_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <description>Managed By Workflow</description>
    <label>Billing Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/CallRevu_Contract__c.field-meta.xml
<CustomField>
    <fullName>CallRevu_Contract__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Service Agreement Products</relationshipLabel>
    <relationshipName>Service_Agreement_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/First_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Invoice_Date__c</fullName>
    <label>First Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Invoice_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Quantity__c</fullName>
    <formula>If( !Product__r.MRR_Product__c ,1,
If( text(Invoice_Type_To_Create__c )=&quot;First Invoice&quot;, First_Invoice_Quantity__c ,
If( text(Invoice_Type_To_Create__c )=&quot;Last Invoice&quot;, Last_Invoice_Quantity__c ,1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Invoice_Type_To_Create__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type_To_Create__c</fullName>
    <label>Invoice Type To Create</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Invoice</fullName>
            </value>
            <value>
                <fullName>Last Invoice</fullName>
            </value>
            <value>
                <fullName>Monthly Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Last_Monthly_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Monthly_Invoice_Date__c</fullName>
    <label>Last Monthly Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Last_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Last_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Order Line Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Service Agreement Products (Last Order Line Item)</relationshipLabel>
    <relationshipName>Service_Agreement_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Next_Billing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Amount__c</fullName>
    <label>Next Billing Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Next_Billing_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_End_Date__c</fullName>
    <label>Next Billing End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Next_Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Start_Date__c</fullName>
    <description>Calculated By Workflow</description>
    <label>Next Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/PriceBookEntryID__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryID__c</fullName>
    <label>PriceBookEntryID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Contract_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Ready_To_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_To_Invoice__c</fullName>
    <formula>!isblank(  text(Invoice_Type_To_Create__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ready To Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Sent_First_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sent_First_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent First Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Products__c/fields/Sent_Last_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sent_Last_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent Last Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateOrderFromAgreementController.cls
/*
    Developer: Jim Hyland <jon@shippconsulting.com>
    
    Description:
       Controller for the CreateOrderFromAgreement Component
       Test code in CreateOrderFromAgreementTest class.
*/

public class CreateOrderFromAgreementController {
    
    /* Constructor */
    
    public CreateOrderFromAgreementController() {
    }
    
    /* Static Methods */
    
    @AuraEnabled
    public static CreateOrderReturn buildOrder(Id recordId, /*String month, String year,*/ Boolean fromCreateOrders) {
        AsyncApexJob batchJob;
        for (AsyncApexJob job : [select id from AsyncApexJob where apexClass.name = 'CreateOrderFromAgreement_Batch' 
                and status != 'Aborted' and status != 'Failed' and status != 'Completed' limit 1]) {
            batchJob = job;
        }
        if (batchJob == null) {
            List<Billing_Agreement__c> agreements = [select Id from Billing_Agreement__c where ready_to_invoice__c = true limit 1];
            if (!Test.isRunningTest() && agreements.isEmpty()) {
                return new CreateOrderReturn('There are no Billing Agreements Ready to Invoice.' /*, false*/);
            }
            Id userId = UserInfo.getUserId();
            CreateOrderFromAgreement_Batch batch = new CreateOrderFromAgreement_Batch(/*month, year, */ recordId, fromCreateOrders, userId);
            if (Test.isRunningTest()) {
                CreateOrderFromAgreement_Batch.testBillingIds.add(agreements[0].Id);
            }
            database.executeBatch(batch, 1);
            return new CreateOrderReturn(null/*, false*/);
        }
        return new CreateOrderReturn('A Billing Batch is already queued.' /*, false*/);
    }
    
    @AuraEnabled
    public static CreateOrderReturn buildOrderFromBilling(Id recordId) {
        AsyncApexJob batchJob;
        for (AsyncApexJob job : [select id from AsyncApexJob where apexClass.name = 'CreateOrderFromAgreement_Batch' 
                and status != 'Aborted' and status != 'Failed' and status != 'Completed' limit 1]) {
            batchJob = job;
        }
        if (batchJob == null) {
            List<Billing_Agreement__c> agreements = [select Id from Billing_Agreement__c where ready_to_invoice__c = true 
                and Id = :recordId limit 1];
            if (!Test.isRunningTest() && agreements.isEmpty()) {
                return new CreateOrderReturn('There are no Billing Agreements Ready to Invoice.' /*, false*/);
            }
            Id userId = UserInfo.getUserId();
            CreateOrderFromAgreement_Batch batch = new CreateOrderFromAgreement_Batch(recordId, userId);
            database.executeBatch(batch, 1);
            return new CreateOrderReturn(null/*, false*/); 
        }
        return new CreateOrderReturn('A Billing Batch is already queued.' /*, false*/);
    }
    
    public static void buildOrders(Billing_Agreement__c billing) {
        system.debug('==> in build');
        String theName = billing.Service_Agreement__r.Name + '-' + billing.Bill_To_Account__r.name;
        theName = theName.length() <= 80 ? theName : theName.subString(0, 80);
        Id pricebookId = Test.isRunningTest() ? Test.getStandardPricebookId() : [select Id from Pricebook2 where isStandard = true].Id;
        Order theOrder = new Order(AccountId = billing.Service_Agreement__r.Service_Location__c, Bill_to_Account__c = billing.Bill_to_Account__c,
            Billing_Agreement__c = billing.Id, Name = theName, EffectiveDate = billing.Next_Billing_Start_Date__c,
            EndDate = billing.Next_Billing_End_Date__c, Type = 'Invoice', Invoice_Type__c = billing.Service_Agreement__r.Last_Opportunity_Change_Type__c,
            Service_Agreement__c = billing.Service_Agreement__c, Status = 'Draft', 
            Pricebook2ID = /*billing.Service_Agreement__r.Price_Book__c*/ pricebookId);
        insert theOrder;
        Map<Id, OrderItem> items = new Map<Id, OrderItem>();
        List<Service_Agreement_Products__c> serviceProducts = [select Last_Order_Date__c, Last_Order_Line_Item__c, PriceBookEntryID__c, Billing_type__c, 
            Next_Billing_Start_Date__c, Next_Billing_End_Date__c, Invoice_Quantity__c, Next_Billing_Amount__c, Price_Per_Unit__c, product__c,
            Invoice_Type_To_Create__c, Sent_First_Invoice__c, Sent_Last_Invoice__c, First_Invoice_Date__c, Last_Invoice_Date__c, Effective_date__c, 
            End_Date__c, Last_Monthly_Invoice_Date__c from Service_Agreement_Products__c 
            where (CallRevu_Contract__c = :billing.Service_Agreement__c and Ready_To_Invoice__c = true)];
        Map<Id, Id> entryByProductId = new Map<Id, Id>();
        for (Service_Agreement_Products__c product : serviceProducts) {
            entryByProductId.put(product.product__c, null);
        }
        for (PricebookEntry entry : [select product2Id from pricebookEntry 
                where Pricebook2Id = :pricebookId and product2Id in :entryByProductId.keySet()]) {
            entryByProductId.put(entry.product2Id, entry.Id);
        }
        for (Service_Agreement_Products__c product : serviceProducts) {
            items.put(product.Id, new OrderItem(PricebookEntryId = /*product.PriceBookEntryID__c*/entryByProductId.get(product.product__c), 
                Billing_Type__c = product.Billing_type__c,
                ServiceDate = product.Next_Billing_Start_Date__c, EndDate = product.Next_Billing_End_Date__c, Quantity = product.Invoice_Quantity__c,
                Invoice_Type__c = product.Invoice_Type_To_Create__c, Service_Agreement_Product__c = product.Id, UnitPrice = product.Price_Per_Unit__c, 
                orderId = theOrder.Id));
        }
        if (!Test.isRunningTest()) {
            insert items.values();
        }
        for (Service_Agreement_Products__c product : serviceProducts) {
            if (product.Invoice_Type_To_Create__c == 'First Invoice') {
                product.Sent_First_Invoice__c = true;
                product.First_Invoice_Date__c = product.Effective_Date__c;
            }
            if (product.Invoice_Type_To_Create__c == 'Last Invoice') {
                product.Sent_Last_Invoice__c = true;
                product.Last_Invoice_Date__c = product.End_Date__c;
            }
            if (product.Invoice_Type_To_Create__c == 'Monthly') {
                product.Last_Monthly_Invoice_Date__c = billing.Next_Billing_Start_Date__c;
            }
           /* product.Last_Order_Date__c = billing.Next_Billing_End_Date__c;*/
            product.Last_Order_Line_Item__c = items.get(product.Id).Id;
            product.Invoice_Type_To_Create__c = null;
        }
        update serviceProducts;
        update new Billing_Agreement__c(Id = billing.Id, ready_to_invoice__c = false);
    }
    
    /* Inner Classes */
    
    public class CreateOrderReturn {
        
        @AuraEnabled
        public String message { get; private set; }
     /*   @AuraEnabled
        public List<String> months { get; private set; }
        @AuraEnabled
        public List<String> years { get; private set; } */
        
        public CreateOrderReturn(String msg/*, Boolean setup*/) {
            message = msg;
           /* if (setup) {
                years = new List<String>{ '--None--', String.valueOf(system.today().addYears(-1).year()), String.valueOf(system.today().year()), 
                    String.valueOf(system.today().addYears(1).year())};
                months = new List<String>{ '--None--', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
                    'November', 'December' };
            }*/
        }
    }
}