force-app/main/default/objects/Active_Employees__c/Active_Employees__c.object-meta.xml
<CustomObject>
    <label>Active Employee</label>
    <nameField>
        <label>Active Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Employees__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Active Employees</relationshipLabel>
    <relationshipName>Active_Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Active_Employees__c/fields/Telephone_PIN__c.field-meta.xml
<CustomField>
    <fullName>Telephone_PIN__c</fullName>
    <label>Telephone PIN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Active_Employees__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Appt Coordinator</fullName>
            </value>
            <value>
                <fullName>Asst Service Mgr.</fullName>
            </value>
            <value>
                <fullName>Asst SM</fullName>
            </value>
            <value>
                <fullName>BDC Agent</fullName>
            </value>
            <value>
                <fullName>BDC Director</fullName>
            </value>
            <value>
                <fullName>BDC Mgr.</fullName>
            </value>
            <value>
                <fullName>BDC Sales</fullName>
            </value>
            <value>
                <fullName>BDC Service</fullName>
            </value>
            <value>
                <fullName>Body Estimator</fullName>
            </value>
            <value>
                <fullName>Body Shop Manager</fullName>
            </value>
            <value>
                <fullName>CallRevu Employee</fullName>
            </value>
            <value>
                <fullName>CallRevu PM</fullName>
            </value>
            <value>
                <fullName>CallRevu Test</fullName>
            </value>
            <value>
                <fullName>Cashier</fullName>
            </value>
            <value>
                <fullName>Controller</fullName>
            </value>
            <value>
                <fullName>Customer Relations Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>DX Manager</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Fin Agent</fullName>
            </value>
            <value>
                <fullName>Fin Director</fullName>
            </value>
            <value>
                <fullName>Fin Mgr.</fullName>
            </value>
            <value>
                <fullName>Fixed Ops Director</fullName>
            </value>
            <value>
                <fullName>Fleet Mgr</fullName>
            </value>
            <value>
                <fullName>Founder/CEO</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>Greeter</fullName>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ad_Source__c/Ad_Source__c.object-meta.xml
<CustomObject>
    <label>Ad Source</label>
    <nameField>
        <label>Ad Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ad_Source__c/fields/Ad_Source__c.field-meta.xml
<CustomField>
    <fullName>Ad_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ad Source</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ad Sources (Ad Source)</relationshipLabel>
    <relationshipName>Ad_Sources1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Area_Code__c</fullName>
    <label>Area Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/CallRevu_Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>CallRevu_Tracking_Number__c</fullName>
    <label>CallRevu Tracking Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Currently_Posted_Number__c.field-meta.xml
<CustomField>
    <fullName>Currently_Posted_Number__c</fullName>
    <label>Currently Posted Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DH</fullName>
            </value>
            <value>
                <fullName>DH Local</fullName>
            </value>
            <value>
                <fullName>Resp Org</fullName>
            </value>
            <value>
                <fullName>DH Local (Dealer)</fullName>
            </value>
            <value>
                <fullName>Login Provided</fullName>
            </value>
            <value>
                <fullName>New Local</fullName>
            </value>
            <value>
                <fullName>New Local (Dealer)</fullName>
            </value>
            <value>
                <fullName>New TFN</fullName>
            </value>
            <value>
                <fullName>New TFN (Dealer)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Posted_Number_Provided_By__c.field-meta.xml
<CustomField>
    <fullName>Posted_Number_Provided_By__c</fullName>
    <label>Posted Number Provided By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto.com</fullName>
            </value>
            <value>
                <fullName>Autobytel</fullName>
            </value>
            <value>
                <fullName>Auto One</fullName>
            </value>
            <value>
                <fullName>AutoTrader</fullName>
            </value>
            <value>
                <fullName>CallBright</fullName>
            </value>
            <value>
                <fullName>CallMeasurement</fullName>
            </value>
            <value>
                <fullName>CallSource</fullName>
            </value>
            <value>
                <fullName>Carfax</fullName>
            </value>
            <value>
                <fullName>CarGurus</fullName>
            </value>
            <value>
                <fullName>Cars.com</fullName>
            </value>
            <value>
                <fullName>CarsforSale</fullName>
            </value>
            <value>
                <fullName>CDK</fullName>
            </value>
            <value>
                <fullName>Cobalt</fullName>
            </value>
            <value>
                <fullName>Dealer.com</fullName>
            </value>
            <value>
                <fullName>Dealer.com SNE</fullName>
            </value>
            <value>
                <fullName>Dealer eProcess</fullName>
            </value>
            <value>
                <fullName>Dealer Inspire</fullName>
            </value>
            <value>
                <fullName>DealerOn</fullName>
            </value>
            <value>
                <fullName>DealerRater</fullName>
            </value>
            <value>
                <fullName>DealerSocket/DealerFire</fullName>
            </value>
            <value>
                <fullName>Dominion</fullName>
            </value>
            <value>
                <fullName>Edmunds</fullName>
            </value>
            <value>
                <fullName>Ford Direct</fullName>
            </value>
            <value>
                <fullName>FZ Automotive</fullName>
            </value>
            <value>
                <fullName>KBB</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Search Optics</fullName>
            </value>
            <value>
                <fullName>TrueCar</fullName>
            </value>
            <value>
                <fullName>VinSolutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Rep_Email__c.field-meta.xml
<CustomField>
    <fullName>Rep_Email__c</fullName>
    <label>Rep Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Rep_Name__c</fullName>
    <label>Rep Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Rings_to__c.field-meta.xml
<CustomField>
    <fullName>Rings_to__c</fullName>
    <label>Rings-to</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Ad Sources</relationshipLabel>
    <relationshipName>Ad_Sources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <label>Service Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CallRevu_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Partner_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Partner_Implementation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Implementation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement (Service Location)</relationshipLabel>
    <relationshipName>Service_Agreement2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Enrollment Started</fullName>
            </value>
            <value>
                <fullName>Implementation Call Scheduled</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>OK to Launch</fullName>
            </value>
            <value>
                <fullName>Launched</fullName>
            </value>
            <value>
                <fullName>Enrollment</fullName>
                <isActive>false</isActive>
                <label>Enrollment</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Launch Approved</fullName>
                <isActive>false</isActive>
                <label>Launch Approved</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Setup In Process</fullName>
                <isActive>false</isActive>
                <label>Setup In Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestFileLoadController.cls
/*
 * Developer: Jim Hyland <jon@shippconsulting.com>
 *  
 * Description: Controller for page for ImportEmployees page.
 *
 * Test code in ContractUpdateTest class.
 */
public class TestFileLoadController {

    /* Variables */
    
    private List<Ad_Source__c> ads;
    public Service_Agreement__c company { get; set; }
    private List<Active_Employees__c> employees;
    public List<String> errorMsg { get; private set; }
    public Boolean loadAdSources { get; private set; }
    public Attachment newAttachment { get; set; }
  
    /* Constructor */
    
    public TestFileLoadController() {
        newAttachment = new Attachment(); 
        loadAdSources = ApexPages.currentPage().getParameters().containsKey(ContractUpdateController.LOAD_AD_SOURCES);
        if (ApexPages.currentPage().getParameters().containsKey(ContractUpdateController.CONTRACT_ID_PARAM)) {
            buildCompany(ApexPages.currentPage().getParameters().get(ContractUpdateController.CONTRACT_ID_PARAM));
        } else {
            errorMsg = new List<String>();
            errorMsg.add('Missing account id in url.  Please contact your administrator.');
            return;
        }
        List<ContractUpdateController.Employee> emps = new List<ContractUpdateController.Employee>();
        employees = new List<Active_Employees__c>();
        emps = ContractUpdateController.buildEmployees(company.Id);
        for (ContractUpdateController.Employee emp : emps) {
            emp.employee.Id = emp.Id;
            employees.add(emp.employee);
        }
        List<ContractUpdateController.Ad> theAds = new List<ContractUpdateController.Ad>();
        ads = new List<Ad_Source__c>();
        theAds = ContractUpdateController.buildAds(company.Id);
        for (ContractUpdateController.Ad ad : theAds) {
            ad.ad.Id = ad.Id;
            ads.add(ad.ad);
        }
    } 
    
    /* Instance Methods */
    
    private void buildCompany(Id companyId) {
        company = [select partner_implementation__c, Service_Location__r.partner_logo_url__c, Bill_To_Account__r.partner_image_width__c, 
            Bill_To_Account__r.partner_image_height__c from Service_Agreement__c where Id = :companyId];
    } 
    
    public PageReference cancelImport() {
        PageReference nextPage = new PageReference('/apex/contractupdate?' + ContractUpdateController.CONTRACT_ID_PARAM + '=' 
            + ApexPages.currentPage().getParameters().get(ContractUpdateController.CONTRACT_ID_PARAM)
            + '&' + ContractUpdateController.CONTACT_ID_PARAM + '=' 
            + ApexPages.currentPage().getParameters().get(ContractUpdateController.CONTACT_ID_PARAM));
        nextpage.setRedirect(true);
        return nextPage;
    } 
    
    public void previewFile() { 
        errorMsg = null;
        if (String.isBlank(newAttachment.name)) {
            errorMsg = new List<String>();
            errorMsg.add('A file must be selected.');
            return;
        }
        if (newAttachment.body == null || newAttachment.body.size() == 0) {
            errorMsg = new List<String>();
            errorMsg.add('The file is empty.  Please import a different file.');
            return;
        }
        String b64 = EncodingUtil.base64Encode(newAttachment.body);
        newAttachment.body = EncodingUtil.base64Decode(b64);
        String strUrlUTF8 = newAttachment.body.toString();
        String body = EncodingUtil.urlDecode(strUrlUTF8, 'UTF-8');
        List<String> parsedBody = parseBody(body);
        
        // verify attachment format
        errorMsg = new List<String>();
        Integer numFields = loadAdSources ? ContractUpdateController.NUM_OF_AD_FIELDS : ContractUpdateController.NUM_OF_FIELDS;
        if (!parsedBody.isEmpty() && parsedBody.size() < numFields - 1) {
            errorMsg.add('Incorrect file format.\n' + body);
            return;
        } 
        String lastHeading = loadAdSources ? ContractUpdateController.LAST_AD_HEADING : ContractUpdateController.LAST_HEADING;
        if (!parsedBody.isEmpty() && parsedBody[numFields - 1].toLowerCase() == lastHeading) {
            String result = loadAdSources ? processAdFile(parsedBody, 
                    ApexPages.currentPage().getParameters().get(ContractUpdateController.CONTRACT_ID_PARAM), ads, numFields) :
                processFile(parsedBody, ApexPages.currentPage().getParameters().get(ContractUpdateController.CONTRACT_ID_PARAM),
                    employees, numFields);
            if (result != null) {
                errorMsg.add('Error Importing File: ' + result + '\n' + body); 
            } else {
                errorMsg.add('File successfully imported.');
            }
        } else {
            errorMsg.add('Incorrect file format.\n' + body); 
        } 
    }
    
    /* Static Methods */
   
    private static List<String> parseBody(String body) { 
        
        // check for null fields
        while (body.indexOf(',,') >= 0 || body.indexOf('\n\n') >= 0 || body.indexOf('\r\r') >= 0 
                || body.indexOf('\n\r') >= 0 || body.indexOf('\r\n') >= 0 || body.indexOf('\r') >= 0
                || body.indexOf('\r\n\r\n') >= 0 || body.indexOf('\n\r\n\r') >= 0) {
            body = body.replace(',,', ', ,');
            body = body.replace('\r\n\r\n', '\n');
            body = body.replace('\n\r\n\r', '\n');
            body = body.replace('\n\n', '\n');
            body = body.replace('\r\r', '\n');
            body = body.replace('\n\r', '\n');
            body = body.replace('\r\n', '\n');
            body = body.replace('\r', '\n');
        }
        
        // parse body
        List<String> lines = body.split('\n', 0);
        while (!lines.isEmpty() && (String.isBlank(lines[0]) || String.isBlank(lines[lines.size() - 1]))) {
            if (String.isBlank(lines[0])) {
                lines.remove(0);
            }
            if (String.isBlank(lines[lines.size() - 1])) {
                lines.remove(lines.size() - 1);
            }
        }
        List<String> parsedBody = new List<String>();
        String tempLine;
        List<String> fieldsOnLine;
        for (String currentLine : lines) {
            if (currentLine.endsWith(',')) {
                currentLine += ' ';
            }
            while (currentLine.contains('\"')) {
                tempLine = currentLine.subString(0, currentLine.indexOf('\"'));
                if (tempLine.length() > 1) {
                    fieldsOnLine = tempLine.split(',', 0);
                    parsedBody.addAll(fieldsOnLine);
                }
                tempLine = currentLine.subString(currentLine.indexOf('\"') + 1, currentLine.length());
                parsedBody.add(tempLine.subString(0, tempLine.indexOf('\"')));
                currentLine = tempLine.indexOf('\"') + 2 < tempLine.length() && tempLine.indexOf('\"') < tempLine.length() ? 
                    tempLine.subString(tempLine.indexOf('\"') + 2, tempLine.length()) : '';
            }
            if (currentLine.length() > 1) {
                fieldsOnLine = currentLine.split(',', 0);
                parsedBody.addAll(fieldsOnLine);
            }
        }
        return parsedBody;
    }
    
    private static String processAdFile(List<String> attachment, Id companyId, List<Ad_Source__c> ads, Integer numFields) { 
        List<Ad_Source__c> importedAds = new List<Ad_Source__c>();
        Set<String> existingAds = new Set<String>();
        for (Ad_Source__c ad : ads) {
            existingAds.add(ad.method__c + ' ' + ad.name + ' ' + ad.Area_Code__c + ' ' + ad.Rep_Email__c);
        } 
        for (Integer i = numFields; i < attachment.size(); i += numFields) {
            if (!existingAds.contains(attachment[i] + ' ' + attachment[i + 1] + ' ' + attachment[i + 2] + ' ' + attachment[i + 8])) {
                importedAds.add(new Ad_Source__c(Service_Agreement__c = companyId, method__c = attachment[i], name = attachment[i + 1], 
                   area_code__c = attachment[i + 2], Currently_Posted_Number__c = attachment[i + 3], CallRevu_Tracking_Number__c = attachment[i + 4],
                   Rings_to__c = attachment[i + 5], Posted_Number_Provided_By__c = attachment[i + 6], Rep_Name__c = attachment[i + 7], 
                   Rep_Email__c = attachment[i + 8], Comments__c = attachment[i + 9]));
            }
        }
        try {
            insert importedAds;
        } catch (Exception e) {
            return e.getMessage();
        } 
        return null;
    } 
    
    private static String processFile(List<String> attachment, Id companyId, List<Active_Employees__c> employees, Integer numFields) { 
        List<Active_Employees__c> importedEmployees = new List<Active_Employees__c>();
        Set<String> existingEmployees = new Set<String>();
        for (Active_Employees__c employee : employees) {
            existingEmployees.add(employee.first_name__c + ' ' + employee.last_name__c + ' ' + employee.email__c);
        }
        for (Integer i = numFields; i < attachment.size(); i += numFields) {
            if (!existingEmployees.contains(attachment[i] + ' ' + attachment[i + 1] + ' ' + attachment[i + 4])) {
                importedEmployees.add(new Active_Employees__c(Service_Agreement__c = companyId, first_name__c = attachment[i], 
                    last_name__c = attachment[i + 1], title__c = attachment[i + 2], email__c = attachment[i + 3],
                    cell_phone__c = attachment[i + 4], Telephone_PIN__c = attachment[i + 5], status__c = attachment[i + 6]));
            }
        }
        try {
            insert importedEmployees;
        } catch (Exception e) {
            return e.getMessage();
        }
        return null;
    } 
}