force-app/main/default/objects/Active_Employees__c/Active_Employees__c.object-meta.xml
<CustomObject>
    <label>Active Employee</label>
    <nameField>
        <label>Active Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Employees__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Active Employees</relationshipLabel>
    <relationshipName>Active_Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/Ad_Source__c.object-meta.xml
<CustomObject>
    <label>Ad Source</label>
    <nameField>
        <label>Ad Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ad_Source__c/fields/Ad_Source__c.field-meta.xml
<CustomField>
    <fullName>Ad_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ad Source</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ad Sources (Ad Source)</relationshipLabel>
    <relationshipName>Ad_Sources1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ad_Source__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Ad Sources</relationshipLabel>
    <relationshipName>Ad_Sources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Collection_HTML__c/Data_Collection_HTML__c.object-meta.xml
<CustomObject>
    <description>Used for data collection landing page.</description>
    <label>Data Collection HTML</label>
    <nameField>
        <label>Data Collection HTML Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Collection HTML</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Collection_HTML__c/fields/Currently_Displaying__c.field-meta.xml
<CustomField>
    <fullName>Currently_Displaying__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Currently Displaying</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Collection_HTML__c/fields/HTML__c.field-meta.xml
<CustomField>
    <fullName>HTML__c</fullName>
    <label>HTML</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <label>Service Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement__c/fields/Authorization_Contact__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorization Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/CRM__c.field-meta.xml
<CustomField>
    <fullName>CRM__c</fullName>
    <label>CRM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advent</fullName>
            </value>
            <value>
                <fullName>Arcadium (Partnered with CDK)</fullName>
            </value>
            <value>
                <fullName>AutoSoft</fullName>
            </value>
            <value>
                <fullName>CarResearch</fullName>
            </value>
            <value>
                <fullName>CDK</fullName>
            </value>
            <value>
                <fullName>Contact Management (Reynolds)</fullName>
            </value>
            <value>
                <fullName>CRM Suite</fullName>
                <label>CRM Suite (iMagic)</label>
            </value>
            <value>
                <fullName>D2C Media</fullName>
            </value>
            <value>
                <fullName>DealerMine</fullName>
            </value>
            <value>
                <fullName>DealerPeak</fullName>
            </value>
            <value>
                <fullName>DealerSocket</fullName>
            </value>
            <value>
                <fullName>Dominion (AutoBase CRMSuite)</fullName>
            </value>
            <value>
                <fullName>DriveCentric</fullName>
            </value>
            <value>
                <fullName>eLead1</fullName>
            </value>
            <value>
                <fullName>FourOneLabs</fullName>
            </value>
            <value>
                <fullName>HigherGear</fullName>
            </value>
            <value>
                <fullName>Interactive360</fullName>
            </value>
            <value>
                <fullName>LIS CRM</fullName>
            </value>
            <value>
                <fullName>Momentum</fullName>
            </value>
            <value>
                <fullName>Oplogic</fullName>
            </value>
            <value>
                <fullName>ProMax</fullName>
            </value>
            <value>
                <fullName>VinSolutions</fullName>
            </value>
            <value>
                <fullName>Votenza</fullName>
            </value>
            <value>
                <fullName>ZoHo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/CRM_Password__c.field-meta.xml
<CustomField>
    <fullName>CRM_Password__c</fullName>
    <label>CRM Password</label>
    <length>30</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/CRM_User_Name__c.field-meta.xml
<CustomField>
    <fullName>CRM_User_Name__c</fullName>
    <label>CRM User Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current Call Tracker Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CallBright</fullName>
            </value>
            <value>
                <fullName>CallFire</fullName>
            </value>
            <value>
                <fullName>CallRail</fullName>
            </value>
            <value>
                <fullName>CallSource</fullName>
            </value>
            <value>
                <fullName>Car Wars/Call Box/CI</fullName>
            </value>
            <value>
                <fullName>CRM - Dominion Vision/Direct Connect</fullName>
            </value>
            <value>
                <fullName>CRM - VinSolutions/Call Tracking</fullName>
            </value>
            <value>
                <fullName>DialogTech</fullName>
            </value>
            <value>
                <fullName>IAT/InteractiveTel</fullName>
            </value>
            <value>
                <fullName>Marchex</fullName>
            </value>
            <value>
                <fullName>Marcom Results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>ProActive Dealer Solutions</fullName>
            </value>
            <value>
                <fullName>RingDNA</fullName>
            </value>
            <value>
                <fullName>Who’sCalling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Fri_Closed__c.field-meta.xml
<CustomField>
    <fullName>Fri_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fri Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Kick_off_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Kick_off_Event_ID__c</fullName>
    <label>Kick-off Event ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Mon_Closed__c.field-meta.xml
<CustomField>
    <fullName>Mon_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mon Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Preferred_Contact_For_Billing__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Contact_For_Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Contact For Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Returning_From_Import_Employees__c.field-meta.xml
<CustomField>
    <fullName>Returning_From_Import_Employees__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Returning From Import Employees</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Sat_Closed__c.field-meta.xml
<CustomField>
    <fullName>Sat_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sat Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Secondary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement (Service Location)</relationshipLabel>
    <relationshipName>Service_Agreement2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Enrollment Started</fullName>
            </value>
            <value>
                <fullName>Implementation Call Scheduled</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>OK to Launch</fullName>
            </value>
            <value>
                <fullName>Launched</fullName>
            </value>
            <value>
                <fullName>Enrollment</fullName>
                <isActive>false</isActive>
                <label>Enrollment</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Launch Approved</fullName>
                <isActive>false</isActive>
                <label>Launch Approved</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Setup In Process</fullName>
                <isActive>false</isActive>
                <label>Setup In Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Sun_Closed__c.field-meta.xml
<CustomField>
    <fullName>Sun_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sun Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Thu_Closed__c.field-meta.xml
<CustomField>
    <fullName>Thu_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thu Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Tue_Closed__c.field-meta.xml
<CustomField>
    <fullName>Tue_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tue Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Wed_Closed__c.field-meta.xml
<CustomField>
    <fullName>Wed_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wed Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContractUpdateTest.cls
/*
    Developer:  Jim Hyland <jon@shippconsulting.com>
    
    Description:
       Tests for ContractUpdateController
*/
@isTest
public class ContractUpdateTest {
     
    /* Test Methods */
    
    @isTest
    private static void testContractUpdateController() {
        
        // set up test data
        Account account = TestUtil.createAccount();
        Account badAccount = TestUtil.createAccount();
        Contact contact = TestUtil.generateContact(account.Id);
        Contact secondaryContact = TestUtil.createContact(account.Id);
        Contact billingContact = TestUtil.createContact(account.Id);
        contact.firstName = 'abc';
        contact.email = 'j@j.com';
        insert contact;
        Contact badContact = TestUtil.createContact(account.Id);
        Service_Agreement__c contract = new Service_Agreement__c(Service_Location__c = account.Id, Authorization_Contact__c = contact.Id,
            crm__c = 'eLead1', secondary_contact__c = secondaryContact.Id, Preferred_Contact_For_Billing__c = billingContact.Id,
            current__c = 'CallBright', is_test__c = true);
        Service_Agreement__c badContract = new Service_Agreement__c(Service_Location__c = account.Id, Authorization_Contact__c = contact.Id);
        insert new List<Service_Agreement__c> { contract, badContract };
        insert new Event(Type = 'Call', status__c = 'Open', startDateTime = system.now(), endDateTime = system.now().addMinutes(30));
         
        // run tests
        PageReference pageRef = Page.ContractUpdate;
        Test.setCurrentPage(pageRef);
        ContractUpdateController con = new ContractUpdateController();
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTRACT_ID_PARAM, badContract.Id);
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTACT_ID_PARAM, badContact.Id);
        con = new ContractUpdateController();
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTRACT_ID_PARAM, contract.Id);
        con = new ContractUpdateController();
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTACT_ID_PARAM, contact.Id);
        con = new ContractUpdateController();
        con.lastname = contact.lastName;
        con.contact.firstName = contact.firstName;
        con.contact.email = contact.email;
        con.contact.mobilePhone='508-123-1111';
        con.setUpAuthorizationContact();
        con.contact.phone='508-123-1112';
        con.setUpAuthorizationContact();
        con.finalAuthentication();
        con.lastname = contact.lastName;
        con.contact.firstName = contact.firstName;
        con.contact.email = contact.email;
        con.finalAuthentication();
        con.contact.email = 'test@test.com';
        con.finalAuthentication();
        con.updateAd();
        con.updateCompany();
        con.updateEmployee();
        con.saveAd();
        con.cancelAd();
        con.saveAd();
        con.updateEmployee();
        con.saveAd();
        con.saveAd();
        con.saveAd();
        con.defaultRep();
        con.deleteAd(); 
        con.saveDealershipStay();
        con.fromCheckSave = true;
        con.saveEmployees();
        con.endSession();
        con.endSession();
        con.exportCSV();
    } 
    
    @isTest
    private static void testContractUpdateControllerContinued() {
        // set up test data
        Account account = TestUtil.createAccount();
        Account badAccount = TestUtil.createAccount();
        Contact contact = TestUtil.generateContact(account.Id);
        Contact secondaryContact = TestUtil.createContact(account.Id);
        Contact billingContact = TestUtil.createContact(account.Id);
        contact.firstName = 'abc';
        contact.email = 'j@j.com';
        insert contact;
        Contact badContact = TestUtil.createContact(account.Id);
        Service_Agreement__c contract = new Service_Agreement__c(Service_Location__c = account.Id, Authorization_Contact__c = contact.Id,
            crm__c = 'eLead1', secondary_contact__c = secondaryContact.Id, Preferred_Contact_For_Billing__c = billingContact.Id,
            current__c = 'CallBright', is_test__c = true);
        Service_Agreement__c badContract = new Service_Agreement__c(Service_Location__c = account.Id, Authorization_Contact__c = contact.Id, 
            is_test__c = true);
        insert new List<Service_Agreement__c> { contract, badContract };
        insert new Event(Type = 'Call', status__c = 'Open', startDateTime = system.now(), endDateTime = system.now().addMinutes(30));
        Blob badAttachmentBody1 = Blob.valueOf('ID NUM.');
        Blob badAttachmentBody2 = Blob.valueOf('First Name,Last Name,Title,Email,Cell Number,Status,Tel. PIN\n'
            + 'first,last,vp,j@j.com,5081231212,1234,Active');
        Blob attachmentBody = Blob.valueOf('First Name,Last Name,Title,Email,Cell Number,Tel. PIN,Status\n'
            + 'first,"last",vp,j@j.com,5081231212,1234,Active');
        Blob adAttachmentBody = Blob.valueOf('Method,Ad Source Name,Area Code,Currently Posted Number,CallRevu Tracking Number,Rings-to,'
            + 'Posted Number Provided By,Rep Name, Rep Email,Comments\n'
            + 'ad,"name",508,5081231212,3,5081231212,a,Rep,r@r.com,abc');
        Attachment attachment = new Attachment();
        insert new Data_Collection_HTML__c(html__c = 'test', Currently_Displaying__c = true);
        Active_Employees__c ae =  new Active_Employees__c(Service_Agreement__c = contract.Id);
        insert ae;
        Ad_Source__c adsource = new Ad_Source__c(Service_Agreement__c = contract.Id);
        insert adsource;
        
        // run tests
        Test.startTest();
        PageReference pageRef = Page.ContractUpdate;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTRACT_ID_PARAM, contract.Id);
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTACT_ID_PARAM, contact.Id);
        ContractUpdateController con = new ContractUpdateController();
        con.scheduleCall();
        con.selectedDay = system.today() + '';
        con.selectedTime = '8:00 am to 8:30 am';
        con.confirmAppointment();
        //con.confirmAppointment();
        con.sync();
        //con.sync();
        con.updateHours();
        con.company.Mon_Closed__c = true;
        con.company.Tue_Closed__c = true;
        con.company.Wed_Closed__c = true;
        con.company.Thu_Closed__c = true;
        con.company.Fri_Closed__c = true;
        con.company.Sat_Closed__c = true;
        con.company.Sun_Closed__c = true;
        con.errorMsg = null;
        con.errorMsg = null;
        con.updateCRM();
        con.errorMsg = null;
        con.saveCRM();
        con.company.crm_user_name__c = 'test';
        con.company.crm_password__c = 'test';
        con.errorMsg = null;
        con.saveCRMStay();
        con.saveCRM();
        con.errorMsg = null;
        con.saveHours();
        con.errorMsg = null;
        con.filterEmployees();
        con.errorMsg = null;
        con.displayPDF();
        con.errorMsg = null;
        con.exportTemplate();
        con.errorMsg = null;
        con.importRoster();
        con.errorMsg = null;
        con.exportAdCSV();
        con.errorMsg = null;
        con.exportAdTemplate();
        con.errorMsg = null;
        con.importAd();
        con.errorMsg = null;
        con.errorMsg = null;
        con.updateCompany();
        con.errorMsg = null;
        con.next();
        con.errorMsg = null;
        //con.next();
        con.errorMsg = null;
        //con.next();
        con.errorMsg = null;
        //con.next();
        con.errorMsg = null;
        //con.next();
        con.errorMsg = null;
        //con.updateCRM();
        con.errorMsg = null;
        con.previous();
        con.errorMsg = null;
        //con.previous();
        con.errorMsg = null;
        //con.previous();
        con.errorMsg = null;
        //con.previous();
        con.errorMsg = null;
        //con.previous();
        con.errorMsg = null;
        con.company.Returning_From_Import_Employees__c = false;
        con.company.kick_off_event_Id__c = 'Test';
        con.updateReturnFlag(); 
        con.saveAllAds();
        con.cancelEmployee();
        con.errorMsg = null;
        con.phoneError();
        con.errorMsg = null;
        con.cancelImport();
        con.errorMsg = null;
        con.deleteEmployee();
        con.errorMsg = null;
        con.saveEmployeesStay();
        con.onboarding();
        PageReference pageRef1 = Page.TestFileLoad;
        Test.setCurrentPage(pageRef1);
        TestFileLoadController con1 = new TestFileLoadController();
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTRACT_ID_PARAM, contract.Id);
        con1 = new TestFileLoadController();
        con1.newAttachment = attachment;
        con1.previewFile();
        con1.newAttachment.Name = 'testAttachment.txt';
        con1.previewFile();
        con1.newAttachment.Body = badAttachmentBody1;
        con1.previewFile();
        con1.newAttachment.Body = badAttachmentBody2;
        con1.previewFile();
        con1.newAttachment.Body = attachmentBody;
        con1.previewFile();
        con1.cancelImport(); 
        ApexPages.currentPage().getParameters().put(ContractUpdateController.LOAD_AD_SOURCES, 'true');
        con1 = new TestFileLoadController();
        con1.newAttachment = attachment;
        con1.newAttachment.Body = adAttachmentBody;
        con1.previewFile();
        PageReference pageRef2 = Page.LandingPage;
        Test.setCurrentPage(pageRef2);
        LandingPageController con2 = new LandingPageController();
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTRACT_ID_PARAM, contract.Id);
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTACT_ID_PARAM, contact.Id);
        con2 = new LandingPageController();
        con2.fillOutSelf();
        con2.next();
        con2.fillOutDesignate();
        con2.authorizationContact.firstName = 'first';
        con2.authorizationContactLastName = 'lasta';
        con2.authorizationContact.email = 'l@l.com';
        con2.secondaryContact.firstName = 'first';
        con2.secondaryContact.lastName = 'lastb';
        con2.secondaryContact.email = 'k@k.com';
        con2.sendEmail();
        Test.stopTest();
    } 
}