force-app/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <label>Service Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement__c/fields/Authorization_Contact__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorization Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/CRM__c.field-meta.xml
<CustomField>
    <fullName>CRM__c</fullName>
    <label>CRM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advent</fullName>
            </value>
            <value>
                <fullName>Arcadium (Partnered with CDK)</fullName>
            </value>
            <value>
                <fullName>AutoSoft</fullName>
            </value>
            <value>
                <fullName>CarResearch</fullName>
            </value>
            <value>
                <fullName>CDK</fullName>
            </value>
            <value>
                <fullName>Contact Management (Reynolds)</fullName>
            </value>
            <value>
                <fullName>CRM Suite</fullName>
                <label>CRM Suite (iMagic)</label>
            </value>
            <value>
                <fullName>D2C Media</fullName>
            </value>
            <value>
                <fullName>DealerMine</fullName>
            </value>
            <value>
                <fullName>DealerPeak</fullName>
            </value>
            <value>
                <fullName>DealerSocket</fullName>
            </value>
            <value>
                <fullName>Dominion (AutoBase CRMSuite)</fullName>
            </value>
            <value>
                <fullName>DriveCentric</fullName>
            </value>
            <value>
                <fullName>eLead1</fullName>
            </value>
            <value>
                <fullName>FourOneLabs</fullName>
            </value>
            <value>
                <fullName>HigherGear</fullName>
            </value>
            <value>
                <fullName>Interactive360</fullName>
            </value>
            <value>
                <fullName>LIS CRM</fullName>
            </value>
            <value>
                <fullName>Momentum</fullName>
            </value>
            <value>
                <fullName>Oplogic</fullName>
            </value>
            <value>
                <fullName>ProMax</fullName>
            </value>
            <value>
                <fullName>VinSolutions</fullName>
            </value>
            <value>
                <fullName>Votenza</fullName>
            </value>
            <value>
                <fullName>ZoHo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current Call Tracker Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CallBright</fullName>
            </value>
            <value>
                <fullName>CallFire</fullName>
            </value>
            <value>
                <fullName>CallRail</fullName>
            </value>
            <value>
                <fullName>CallSource</fullName>
            </value>
            <value>
                <fullName>Car Wars/Call Box/CI</fullName>
            </value>
            <value>
                <fullName>CRM - Dominion Vision/Direct Connect</fullName>
            </value>
            <value>
                <fullName>CRM - VinSolutions/Call Tracking</fullName>
            </value>
            <value>
                <fullName>DialogTech</fullName>
            </value>
            <value>
                <fullName>IAT/InteractiveTel</fullName>
            </value>
            <value>
                <fullName>Marchex</fullName>
            </value>
            <value>
                <fullName>Marcom Results</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>ProActive Dealer Solutions</fullName>
            </value>
            <value>
                <fullName>RingDNA</fullName>
            </value>
            <value>
                <fullName>Who’sCalling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Date_Completed_AD_LOA__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed_AD_LOA__c</fullName>
    <label>Date Completed AD/LOA</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Date_Completed_AD_PORT__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed_AD_PORT__c</fullName>
    <label>Date Completed AD/PORT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Date_Completed_CC__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed_CC__c</fullName>
    <label>Date Completed CC</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Date_Completed_RR__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed_RR__c</fullName>
    <label>Date Completed RR</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Date_Completed_WL__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed_WL__c</fullName>
    <label>Date Completed WL</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Preferred_Contact_For_Billing__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Contact_For_Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Contact For Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Secondary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CallRevu_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <label>Service Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Agreement (Service Location)</relationshipLabel>
    <relationshipName>Service_Agreement2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OnboardingChecklistTest.cls
/*
    Developer:  Jim Hyland <jon@shippconsulting.com>
    
    Description:
       Tests for OnboardingChecklistController
*/
@isTest
public class OnboardingChecklistTest {
     
    /* Test Methods */
    
    @isTest
    private static void testOnboardingChecklistController() {
        // set up test data
        Account account = TestUtil.createAccount();
        Contact contact = TestUtil.generateContact(account.Id);
        Contact secondaryContact = TestUtil.createContact(account.Id);
        Contact billingContact = TestUtil.createContact(account.Id);
        contact.firstName = 'abc';
        contact.email = 'j@j.com';
        insert contact;
        Service_Agreement__c contract = new Service_Agreement__c(Service_Location__c = account.Id, Authorization_Contact__c = contact.Id,
            crm__c = 'eLead1', secondary_contact__c = secondaryContact.Id, Preferred_Contact_For_Billing__c = billingContact.Id,
            current__c = 'CallBright', Date_Completed_WL__c = system.now(), Date_Completed_CC__c = DateTime.valueOf('2021-1-23 23:59:00'), 
            Date_Completed_RR__c = DateTime.valueOf('2021-1-31 00:59:00'), Date_Completed_AD_LOA__c = DateTime.valueOf('2021-1-12 12:59:00'),
            Date_Completed_AD_PORT__c = DateTime.valueOf('2021-1-13 13:59:00'), is_test__c = true);
        insert new List<Service_Agreement__c> { contract };
         
        // run tests
        Test.startTest();
        PageReference pageRef1 = Page.OnboardingChecklist;
        Test.setCurrentPage(pageRef1);
        OnboardingChecklistController con1 = new OnboardingChecklistController();
        ApexPages.currentPage().getParameters().put(ContractUpdateController.CONTRACT_ID_PARAM, contract.Id);
        con1 = new OnboardingChecklistController();
        con1.cancelChecklist();
        Test.stopTest();
    } 
}